trigger:
- master

pool:
  vmImage: 'windows-latest'


pool:
  name: Azure Pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet Restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Web/BankManagementSystem.Web.csproj

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: 'Web\bin\Debug\netcoreapp3.1'

